name: AlgoNNexus

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install flake8
      run: pip install flake8
    
    - name: Run linting
      run: flake8 .
    
    - name: Run tests
      run: |
        pip install pytest pytest-cov
        pytest --cov=src
    
    - name: Upload coverage results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
